export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const LOGOUT = 'LOGOUT';

export const FETCH_CLASSES = 'FETCH_CLASSES';
export const CLASSES_FETCHED = 'CLASSES_FETCHED';
export const FETCH_POSTS = 'FETCH_POSTS';
export const POSTS_FETCHED = 'POSTS_FETCHED';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const GROUPS_FETCHED = 'GROUPS_FETCHED';
export const FETCH_GROUP_DETAILS = 'FETCH_GROUP_DETAILS';
export const GROUP_DETAILS_FETCHED = 'GROUP_DETAILS_FETCHED';

export const DO_POST = 'DO_POST';
export const POST_DONE = 'POST_DONE';
export const DO_COMMENT = 'DO_COMMENT';
export const COMMENT_DONE = 'COMMENT_DONE';
export const DO_GROUP = 'DO_GROUP';
export const GROUP_DONE = 'GROUP_DONE';
export const DO_TASK = 'DO_TASK';
export const TASK_DONE = 'TASK_DONE';
export const DO_FOLLOW = 'DO_FOLLOW';
export const FOLLOWED_SUCCESSFULLY = 'FOLLOWED_SUCCESSFULLY';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const USER_DETAILS_UPDATED = 'USER_DETAILS_UPDATED';

export const FETCH_RELATED = 'FETCH_RELATED';
export const RELATED_FETCHED = 'RELATED_FETCHED';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOADING = 'LOADING';