export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const USER_DETAILS = 'USER_DETAILS';
export const LOGOUT = 'LOGOUT';

export const POSTS_FETCHED = 'POSTS_FETCHED';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const USER_DETAILS_UPDATED = 'USER_DETAILS_UPDATED';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOADING = 'LOADING';
