export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const LOGOUT = 'LOGOUT';

export const FETCH_CLASSES = 'FETCH_CLASSES';
export const CLASSES_FETCHED = 'CLASSES_FETCHED';
export const FETCH_POSTS = 'FETCH_POSTS';
export const POSTS_FETCHED = 'POSTS_FETCHED';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const USER_DETAILS_UPDATED = 'USER_DETAILS_UPDATED';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOADING = 'LOADING';